/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as StartDayRouteImport } from './routes/start-day'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsSubmitRouteImport } from './routes/reports/submit'
import { Route as ReportsHistoryRouteImport } from './routes/reports/history'
import { Route as DashboardPairingsRouteImport } from './routes/dashboard/pairings'
import { Route as DashboardEaRouteImport } from './routes/dashboard/ea'
import { Route as DashboardClientsRouteImport } from './routes/dashboard/clients'
import { Route as DashboardAssistantsRouteImport } from './routes/dashboard/assistants'
import { Route as AlertsKanbanRouteImport } from './routes/alerts/kanban'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminPtoRouteImport } from './routes/admin/pto'
import { Route as AdminCoachingNotesRouteImport } from './routes/admin/coaching-notes'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminAlertRulesRouteImport } from './routes/admin/alert-rules'
import { Route as AdminAcceleratorRouteImport } from './routes/admin/accelerator'
import { Route as DashboardPairingsPairingIdRouteImport } from './routes/dashboard/pairings/$pairingId'
import { Route as DashboardClientsClientIdRouteImport } from './routes/dashboard/clients/$clientId'
import { Route as AdminPairingsImportRouteImport } from './routes/admin/pairings/import'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDayRoute = StartDayRouteImport.update({
  id: '/start-day',
  path: '/start-day',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSubmitRoute = ReportsSubmitRouteImport.update({
  id: '/reports/submit',
  path: '/reports/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsHistoryRoute = ReportsHistoryRouteImport.update({
  id: '/reports/history',
  path: '/reports/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPairingsRoute = DashboardPairingsRouteImport.update({
  id: '/dashboard/pairings',
  path: '/dashboard/pairings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEaRoute = DashboardEaRouteImport.update({
  id: '/dashboard/ea',
  path: '/dashboard/ea',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/dashboard/clients',
  path: '/dashboard/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAssistantsRoute = DashboardAssistantsRouteImport.update({
  id: '/dashboard/assistants',
  path: '/dashboard/assistants',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsKanbanRoute = AlertsKanbanRouteImport.update({
  id: '/alerts/kanban',
  path: '/alerts/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPtoRoute = AdminPtoRouteImport.update({
  id: '/admin/pto',
  path: '/admin/pto',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoachingNotesRoute = AdminCoachingNotesRouteImport.update({
  id: '/admin/coaching-notes',
  path: '/admin/coaching-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertRulesRoute = AdminAlertRulesRouteImport.update({
  id: '/admin/alert-rules',
  path: '/admin/alert-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcceleratorRoute = AdminAcceleratorRouteImport.update({
  id: '/admin/accelerator',
  path: '/admin/accelerator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPairingsPairingIdRoute =
  DashboardPairingsPairingIdRouteImport.update({
    id: '/$pairingId',
    path: '/$pairingId',
    getParentRoute: () => DashboardPairingsRoute,
  } as any)
const DashboardClientsClientIdRoute =
  DashboardClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => DashboardClientsRoute,
  } as any)
const AdminPairingsImportRoute = AdminPairingsImportRouteImport.update({
  id: '/admin/pairings/import',
  path: '/admin/pairings/import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start-day': typeof StartDayRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/accelerator': typeof AdminAcceleratorRoute
  '/admin/alert-rules': typeof AdminAlertRulesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/coaching-notes': typeof AdminCoachingNotesRoute
  '/admin/pto': typeof AdminPtoRoute
  '/admin/users': typeof AdminUsersRoute
  '/alerts/kanban': typeof AlertsKanbanRoute
  '/dashboard/assistants': typeof DashboardAssistantsRoute
  '/dashboard/clients': typeof DashboardClientsRouteWithChildren
  '/dashboard/ea': typeof DashboardEaRoute
  '/dashboard/pairings': typeof DashboardPairingsRouteWithChildren
  '/reports/history': typeof ReportsHistoryRoute
  '/reports/submit': typeof ReportsSubmitRoute
  '/admin/pairings/import': typeof AdminPairingsImportRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdRoute
  '/dashboard/pairings/$pairingId': typeof DashboardPairingsPairingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start-day': typeof StartDayRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/accelerator': typeof AdminAcceleratorRoute
  '/admin/alert-rules': typeof AdminAlertRulesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/coaching-notes': typeof AdminCoachingNotesRoute
  '/admin/pto': typeof AdminPtoRoute
  '/admin/users': typeof AdminUsersRoute
  '/alerts/kanban': typeof AlertsKanbanRoute
  '/dashboard/assistants': typeof DashboardAssistantsRoute
  '/dashboard/clients': typeof DashboardClientsRouteWithChildren
  '/dashboard/ea': typeof DashboardEaRoute
  '/dashboard/pairings': typeof DashboardPairingsRouteWithChildren
  '/reports/history': typeof ReportsHistoryRoute
  '/reports/submit': typeof ReportsSubmitRoute
  '/admin/pairings/import': typeof AdminPairingsImportRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdRoute
  '/dashboard/pairings/$pairingId': typeof DashboardPairingsPairingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/coming-soon': typeof ComingSoonRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start-day': typeof StartDayRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/accelerator': typeof AdminAcceleratorRoute
  '/admin/alert-rules': typeof AdminAlertRulesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/coaching-notes': typeof AdminCoachingNotesRoute
  '/admin/pto': typeof AdminPtoRoute
  '/admin/users': typeof AdminUsersRoute
  '/alerts/kanban': typeof AlertsKanbanRoute
  '/dashboard/assistants': typeof DashboardAssistantsRoute
  '/dashboard/clients': typeof DashboardClientsRouteWithChildren
  '/dashboard/ea': typeof DashboardEaRoute
  '/dashboard/pairings': typeof DashboardPairingsRouteWithChildren
  '/reports/history': typeof ReportsHistoryRoute
  '/reports/submit': typeof ReportsSubmitRoute
  '/admin/pairings/import': typeof AdminPairingsImportRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdRoute
  '/dashboard/pairings/$pairingId': typeof DashboardPairingsPairingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coming-soon'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/start-day'
    | '/verify-email'
    | '/admin/accelerator'
    | '/admin/alert-rules'
    | '/admin/announcements'
    | '/admin/coaching-notes'
    | '/admin/pto'
    | '/admin/users'
    | '/alerts/kanban'
    | '/dashboard/assistants'
    | '/dashboard/clients'
    | '/dashboard/ea'
    | '/dashboard/pairings'
    | '/reports/history'
    | '/reports/submit'
    | '/admin/pairings/import'
    | '/dashboard/clients/$clientId'
    | '/dashboard/pairings/$pairingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coming-soon'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/start-day'
    | '/verify-email'
    | '/admin/accelerator'
    | '/admin/alert-rules'
    | '/admin/announcements'
    | '/admin/coaching-notes'
    | '/admin/pto'
    | '/admin/users'
    | '/alerts/kanban'
    | '/dashboard/assistants'
    | '/dashboard/clients'
    | '/dashboard/ea'
    | '/dashboard/pairings'
    | '/reports/history'
    | '/reports/submit'
    | '/admin/pairings/import'
    | '/dashboard/clients/$clientId'
    | '/dashboard/pairings/$pairingId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/coming-soon'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/start-day'
    | '/verify-email'
    | '/admin/accelerator'
    | '/admin/alert-rules'
    | '/admin/announcements'
    | '/admin/coaching-notes'
    | '/admin/pto'
    | '/admin/users'
    | '/alerts/kanban'
    | '/dashboard/assistants'
    | '/dashboard/clients'
    | '/dashboard/ea'
    | '/dashboard/pairings'
    | '/reports/history'
    | '/reports/submit'
    | '/admin/pairings/import'
    | '/dashboard/clients/$clientId'
    | '/dashboard/pairings/$pairingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StartDayRoute: typeof StartDayRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminAcceleratorRoute: typeof AdminAcceleratorRoute
  AdminAlertRulesRoute: typeof AdminAlertRulesRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminCoachingNotesRoute: typeof AdminCoachingNotesRoute
  AdminPtoRoute: typeof AdminPtoRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AlertsKanbanRoute: typeof AlertsKanbanRoute
  DashboardAssistantsRoute: typeof DashboardAssistantsRoute
  DashboardClientsRoute: typeof DashboardClientsRouteWithChildren
  DashboardEaRoute: typeof DashboardEaRoute
  DashboardPairingsRoute: typeof DashboardPairingsRouteWithChildren
  ReportsHistoryRoute: typeof ReportsHistoryRoute
  ReportsSubmitRoute: typeof ReportsSubmitRoute
  AdminPairingsImportRoute: typeof AdminPairingsImportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-day': {
      id: '/start-day'
      path: '/start-day'
      fullPath: '/start-day'
      preLoaderRoute: typeof StartDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/submit': {
      id: '/reports/submit'
      path: '/reports/submit'
      fullPath: '/reports/submit'
      preLoaderRoute: typeof ReportsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/history': {
      id: '/reports/history'
      path: '/reports/history'
      fullPath: '/reports/history'
      preLoaderRoute: typeof ReportsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pairings': {
      id: '/dashboard/pairings'
      path: '/dashboard/pairings'
      fullPath: '/dashboard/pairings'
      preLoaderRoute: typeof DashboardPairingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ea': {
      id: '/dashboard/ea'
      path: '/dashboard/ea'
      fullPath: '/dashboard/ea'
      preLoaderRoute: typeof DashboardEaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/dashboard/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/assistants': {
      id: '/dashboard/assistants'
      path: '/dashboard/assistants'
      fullPath: '/dashboard/assistants'
      preLoaderRoute: typeof DashboardAssistantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/kanban': {
      id: '/alerts/kanban'
      path: '/alerts/kanban'
      fullPath: '/alerts/kanban'
      preLoaderRoute: typeof AlertsKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pto': {
      id: '/admin/pto'
      path: '/admin/pto'
      fullPath: '/admin/pto'
      preLoaderRoute: typeof AdminPtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coaching-notes': {
      id: '/admin/coaching-notes'
      path: '/admin/coaching-notes'
      fullPath: '/admin/coaching-notes'
      preLoaderRoute: typeof AdminCoachingNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alert-rules': {
      id: '/admin/alert-rules'
      path: '/admin/alert-rules'
      fullPath: '/admin/alert-rules'
      preLoaderRoute: typeof AdminAlertRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accelerator': {
      id: '/admin/accelerator'
      path: '/admin/accelerator'
      fullPath: '/admin/accelerator'
      preLoaderRoute: typeof AdminAcceleratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pairings/$pairingId': {
      id: '/dashboard/pairings/$pairingId'
      path: '/$pairingId'
      fullPath: '/dashboard/pairings/$pairingId'
      preLoaderRoute: typeof DashboardPairingsPairingIdRouteImport
      parentRoute: typeof DashboardPairingsRoute
    }
    '/dashboard/clients/$clientId': {
      id: '/dashboard/clients/$clientId'
      path: '/$clientId'
      fullPath: '/dashboard/clients/$clientId'
      preLoaderRoute: typeof DashboardClientsClientIdRouteImport
      parentRoute: typeof DashboardClientsRoute
    }
    '/admin/pairings/import': {
      id: '/admin/pairings/import'
      path: '/admin/pairings/import'
      fullPath: '/admin/pairings/import'
      preLoaderRoute: typeof AdminPairingsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardClientsRouteChildren {
  DashboardClientsClientIdRoute: typeof DashboardClientsClientIdRoute
}

const DashboardClientsRouteChildren: DashboardClientsRouteChildren = {
  DashboardClientsClientIdRoute: DashboardClientsClientIdRoute,
}

const DashboardClientsRouteWithChildren =
  DashboardClientsRoute._addFileChildren(DashboardClientsRouteChildren)

interface DashboardPairingsRouteChildren {
  DashboardPairingsPairingIdRoute: typeof DashboardPairingsPairingIdRoute
}

const DashboardPairingsRouteChildren: DashboardPairingsRouteChildren = {
  DashboardPairingsPairingIdRoute: DashboardPairingsPairingIdRoute,
}

const DashboardPairingsRouteWithChildren =
  DashboardPairingsRoute._addFileChildren(DashboardPairingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute,
  ComingSoonRoute: ComingSoonRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StartDayRoute: StartDayRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminAcceleratorRoute: AdminAcceleratorRoute,
  AdminAlertRulesRoute: AdminAlertRulesRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminCoachingNotesRoute: AdminCoachingNotesRoute,
  AdminPtoRoute: AdminPtoRoute,
  AdminUsersRoute: AdminUsersRoute,
  AlertsKanbanRoute: AlertsKanbanRoute,
  DashboardAssistantsRoute: DashboardAssistantsRoute,
  DashboardClientsRoute: DashboardClientsRouteWithChildren,
  DashboardEaRoute: DashboardEaRoute,
  DashboardPairingsRoute: DashboardPairingsRouteWithChildren,
  ReportsHistoryRoute: ReportsHistoryRoute,
  ReportsSubmitRoute: ReportsSubmitRoute,
  AdminPairingsImportRoute: AdminPairingsImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
